// Code generated by protoc-gen-twirplura v1.0.0, DO NOT EDIT.
// source: protos/svcc/service.proto

package svcc

import context "context"
import json "encoding/json"
import fmt "fmt"

import "github.com/kyawmyintthein/lura-twirp"
import "github.com/luraproject/lura/config"
import "github.com/luraproject/lura/logging"
import twirp "github.com/twitchtv/twirp"
import proto "google.golang.org/protobuf/proto"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ====================
// CService Lura Client
// ====================

type cServiceLuraClient struct {
	id      string
	service CService
	l       logging.Logger
}

// ================
// CService Methods
// ================

const (
	_CServiceMethod_CallServiceC = "CallServiceC"
)

// =======================================================================================
// NewCServiceLuraClient creates a Protobuf client that implements the CService interface.
// =======================================================================================

func NewCServiceLuraClient(config *config.ServiceConfig, id string, client HTTPClient, l logging.Logger, opts ...twirp.ClientOption) (luratwirp.LuraTwirpStub, error) {
	baseURL, err := getBaseURLByCServiceClientID(config)
	if err != nil {
		return nil, err
	}
	protobufClient := NewCServiceProtobufClient(baseURL, client, opts...)
	return &cServiceLuraClient{
		id:      id,
		service: protobufClient,
		l:       l,
	}, nil
}

// =============================
// CService getBaseURLByClientID
// =============================

func getBaseURLByCServiceClientID(config *config.ServiceConfig) (string, error) {
	for _, endpoint := range config.Endpoints {
		_, ok := endpoint.ExtraConfig[luratwirp.TwirpServiceIdentifierConst].(string)
		if ok {
			for _, backend := range endpoint.Backend {
				_, ok := backend.ExtraConfig[luratwirp.TwirpServiceIdentifierConst].(string)
				if ok {
					if len(backend.Host) <= 0 {
						return "", twirp.InternalError("invalid host configuration")
					}
				}
				return backend.Host[0], nil
			}
		}
	}
	return "", twirp.InternalError(fmt.Sprintf("invalid %s", luratwirp.TwirpServiceIdentifierConst))
}

// ==============================================================
// Invoke invoke RPC function regarding given service and method.
// ==============================================================

func (c *cServiceLuraClient) Invoke(ctx context.Context, service string, method string, in proto.Message) (proto.Message, error) {
	switch method {
	case _CServiceMethod_CallServiceC:
		req, ok := in.(*GetServiceCRequest)
		if !ok {
			return nil, twirp.InternalError("invalid protobuf message")
		}
		resp, err := c.service.CallServiceC(ctx, req)
		if err != nil {
			c.l.Error(err, "failed to invoke : ", _CServiceMethod_CallServiceC)
			return resp, err
		}
		return resp, err
	}
	return nil, twirp.InternalError(fmt.Sprintf("invalid %s", luratwirp.TwirpServiceIdentifierConst))
}

// ===================================================================
// Identifier return client identifier to lura-twirp backend registery
// ===================================================================

func (c *cServiceLuraClient) Identifier() string {
	return c.id
}

// ====================================
// Encode convert JSON to proto.Message
// ====================================

func (c *cServiceLuraClient) Encode(ctx context.Context, method string, data []byte) (proto.Message, error) {
	switch method {
	case _CServiceMethod_CallServiceC:
		out := new(GetServiceCRequest)
		err := json.Unmarshal(data, out)
		if err != nil {
			c.l.Error(err, "failed to unmarhsal : ", _CServiceMethod_CallServiceC)
			return out, err
		}
		return out, err
	}
	return nil, twirp.InternalError(fmt.Sprintf("invalid method %s", method))
}

// ====================================
// Decode convert proto.Message to JSON
// ====================================

func (c *cServiceLuraClient) Decode(ctx context.Context, method string, msg proto.Message) ([]byte, error) {
	switch method {
	case _CServiceMethod_CallServiceC:
		out, err := proto.Marshal(msg)
		if err != nil {
			c.l.Error(err, "failed to marshal : ", _CServiceMethod_CallServiceC)
			return out, err
		}
		return out, err
	}
	return nil, twirp.InternalError(fmt.Sprintf("invalid method %s", method))
}
